diff -Naur pam_u2f-1.0.3.old/Makefile.am pam_u2f-1.0.3/Makefile.am
--- pam_u2f-1.0.3.old/Makefile.am	2015-11-26 12:21:14.040128747 +0100
+++ pam_u2f-1.0.3/Makefile.am	2015-11-26 12:21:36.201389562 +0100
@@ -33,10 +33,6 @@
 
 # Release
 
-install-exec-hook:
-	rm -f $(PAMDIR)/pam_u2f.la
-	chmod -f 644 $(PAMDIR)/pam_u2f.so || true
-
 indent:
 	indent -kr -nut -i2 *.c *.h pamu2fcfg/*.c pamu2fcfg/*.h
 	indent -kr -nut -i2 *.c *.h pamu2fcfg/*.c pamu2fcfg/*.h
diff -Naur pam_u2f-1.0.3.old/Makefile.in pam_u2f-1.0.3/Makefile.in
--- pam_u2f-1.0.3.old/Makefile.in	2015-11-26 12:21:14.040128747 +0100
+++ pam_u2f-1.0.3/Makefile.in	2015-11-26 12:21:46.925032864 +0100
@@ -1004,10 +1004,6 @@
 
 # Release
 
-install-exec-hook:
-	rm -f $(PAMDIR)/pam_u2f.la
-	chmod -f 644 $(PAMDIR)/pam_u2f.so || true
-
 indent:
 	indent -kr -nut -i2 *.c *.h pamu2fcfg/*.c pamu2fcfg/*.h
 	indent -kr -nut -i2 *.c *.h pamu2fcfg/*.c pamu2fcfg/*.h
